// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cellchat_prob_boot_cpp
List cellchat_prob_boot_cpp(NumericMatrix dataLavg, NumericMatrix dataRavg, NumericMatrix dataLavgBoot, NumericMatrix dataRavgBoot, NumericMatrix agonist, NumericMatrix antagonist, NumericMatrix agonistBoot, NumericMatrix antagonistBoot, LogicalVector hasAgonist, LogicalVector hasAntagonist, double Kh, double n_power, int nboot);
RcppExport SEXP _CellChatAccelRcpp_cellchat_prob_boot_cpp(SEXP dataLavgSEXP, SEXP dataRavgSEXP, SEXP dataLavgBootSEXP, SEXP dataRavgBootSEXP, SEXP agonistSEXP, SEXP antagonistSEXP, SEXP agonistBootSEXP, SEXP antagonistBootSEXP, SEXP hasAgonistSEXP, SEXP hasAntagonistSEXP, SEXP KhSEXP, SEXP n_powerSEXP, SEXP nbootSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dataLavg(dataLavgSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dataRavg(dataRavgSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dataLavgBoot(dataLavgBootSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dataRavgBoot(dataRavgBootSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type agonist(agonistSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type antagonist(antagonistSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type agonistBoot(agonistBootSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type antagonistBoot(antagonistBootSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type hasAgonist(hasAgonistSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type hasAntagonist(hasAntagonistSEXP);
    Rcpp::traits::input_parameter< double >::type Kh(KhSEXP);
    Rcpp::traits::input_parameter< double >::type n_power(n_powerSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    rcpp_result_gen = Rcpp::wrap(cellchat_prob_boot_cpp(dataLavg, dataRavg, dataLavgBoot, dataRavgBoot, agonist, antagonist, agonistBoot, antagonistBoot, hasAgonist, hasAntagonist, Kh, n_power, nboot));
    return rcpp_result_gen;
END_RCPP
}
// group_tri_mean_cpp
NumericMatrix group_tri_mean_cpp(NumericMatrix data, IntegerVector group, int K);
RcppExport SEXP _CellChatAccelRcpp_group_tri_mean_cpp(SEXP dataSEXP, SEXP groupSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(group_tri_mean_cpp(data, group, K));
    return rcpp_result_gen;
END_RCPP
}
// group_tri_mean_boot_cpp
List group_tri_mean_boot_cpp(NumericMatrix data, IntegerMatrix groupBoot, int K);
RcppExport SEXP _CellChatAccelRcpp_group_tri_mean_boot_cpp(SEXP dataSEXP, SEXP groupBootSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type groupBoot(groupBootSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(group_tri_mean_boot_cpp(data, groupBoot, K));
    return rcpp_result_gen;
END_RCPP
}
// cellchat_prob_from_avg_cpp
List cellchat_prob_from_avg_cpp(NumericMatrix avg, NumericVector avgBoot, IntegerMatrix ligandIdx, IntegerMatrix receptorIdx, IntegerMatrix coAIdx, IntegerMatrix coIIdx, IntegerMatrix agonistIdx, IntegerMatrix antagonistIdx, LogicalVector hasAgonist, LogicalVector hasAntagonist, double Kh, double n_power);
RcppExport SEXP _CellChatAccelRcpp_cellchat_prob_from_avg_cpp(SEXP avgSEXP, SEXP avgBootSEXP, SEXP ligandIdxSEXP, SEXP receptorIdxSEXP, SEXP coAIdxSEXP, SEXP coIIdxSEXP, SEXP agonistIdxSEXP, SEXP antagonistIdxSEXP, SEXP hasAgonistSEXP, SEXP hasAntagonistSEXP, SEXP KhSEXP, SEXP n_powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type avg(avgSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type avgBoot(avgBootSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type ligandIdx(ligandIdxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type receptorIdx(receptorIdxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type coAIdx(coAIdxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type coIIdx(coIIdxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type agonistIdx(agonistIdxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type antagonistIdx(antagonistIdxSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type hasAgonist(hasAgonistSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type hasAntagonist(hasAntagonistSEXP);
    Rcpp::traits::input_parameter< double >::type Kh(KhSEXP);
    Rcpp::traits::input_parameter< double >::type n_power(n_powerSEXP);
    rcpp_result_gen = Rcpp::wrap(cellchat_prob_from_avg_cpp(avg, avgBoot, ligandIdx, receptorIdx, coAIdx, coIIdx, agonistIdx, antagonistIdx, hasAgonist, hasAntagonist, Kh, n_power));
    return rcpp_result_gen;
END_RCPP
}
// cellchat_prob_from_avg_sparse_cpp
List cellchat_prob_from_avg_sparse_cpp(NumericMatrix avg, NumericVector avgBoot, IntegerMatrix ligandIdx, IntegerMatrix receptorIdx, IntegerMatrix coAIdx, IntegerMatrix coIIdx, IntegerMatrix agonistIdx, IntegerMatrix antagonistIdx, LogicalVector hasAgonist, LogicalVector hasAntagonist, double Kh, double n_power);
RcppExport SEXP _CellChatAccelRcpp_cellchat_prob_from_avg_sparse_cpp(SEXP avgSEXP, SEXP avgBootSEXP, SEXP ligandIdxSEXP, SEXP receptorIdxSEXP, SEXP coAIdxSEXP, SEXP coIIdxSEXP, SEXP agonistIdxSEXP, SEXP antagonistIdxSEXP, SEXP hasAgonistSEXP, SEXP hasAntagonistSEXP, SEXP KhSEXP, SEXP n_powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type avg(avgSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type avgBoot(avgBootSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type ligandIdx(ligandIdxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type receptorIdx(receptorIdxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type coAIdx(coAIdxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type coIIdx(coIIdxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type agonistIdx(agonistIdxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type antagonistIdx(antagonistIdxSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type hasAgonist(hasAgonistSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type hasAntagonist(hasAntagonistSEXP);
    Rcpp::traits::input_parameter< double >::type Kh(KhSEXP);
    Rcpp::traits::input_parameter< double >::type n_power(n_powerSEXP);
    rcpp_result_gen = Rcpp::wrap(cellchat_prob_from_avg_sparse_cpp(avg, avgBoot, ligandIdx, receptorIdx, coAIdx, coIIdx, agonistIdx, antagonistIdx, hasAgonist, hasAntagonist, Kh, n_power));
    return rcpp_result_gen;
END_RCPP
}
// cellchat_prob_sparse_stream_cpp
List cellchat_prob_sparse_stream_cpp(NumericMatrix data, IntegerVector group, IntegerMatrix groupBoot, NumericMatrix avg, IntegerMatrix ligandIdx, IntegerMatrix receptorIdx, IntegerMatrix coAIdx, IntegerMatrix coIIdx, IntegerMatrix agonistIdx, IntegerMatrix antagonistIdx, LogicalVector hasAgonist, LogicalVector hasAntagonist, double Kh, double n_power);
RcppExport SEXP _CellChatAccelRcpp_cellchat_prob_sparse_stream_cpp(SEXP dataSEXP, SEXP groupSEXP, SEXP groupBootSEXP, SEXP avgSEXP, SEXP ligandIdxSEXP, SEXP receptorIdxSEXP, SEXP coAIdxSEXP, SEXP coIIdxSEXP, SEXP agonistIdxSEXP, SEXP antagonistIdxSEXP, SEXP hasAgonistSEXP, SEXP hasAntagonistSEXP, SEXP KhSEXP, SEXP n_powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type groupBoot(groupBootSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type avg(avgSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type ligandIdx(ligandIdxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type receptorIdx(receptorIdxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type coAIdx(coAIdxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type coIIdx(coIIdxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type agonistIdx(agonistIdxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type antagonistIdx(antagonistIdxSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type hasAgonist(hasAgonistSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type hasAntagonist(hasAntagonistSEXP);
    Rcpp::traits::input_parameter< double >::type Kh(KhSEXP);
    Rcpp::traits::input_parameter< double >::type n_power(n_powerSEXP);
    rcpp_result_gen = Rcpp::wrap(cellchat_prob_sparse_stream_cpp(data, group, groupBoot, avg, ligandIdx, receptorIdx, coAIdx, coIIdx, agonistIdx, antagonistIdx, hasAgonist, hasAntagonist, Kh, n_power));
    return rcpp_result_gen;
END_RCPP
}
// cellchat_prob_simple_ondemand_cpp
List cellchat_prob_simple_ondemand_cpp(NumericMatrix data, IntegerVector group, IntegerMatrix groupBoot, IntegerVector ligandGene, IntegerVector receptorGene, double Kh, double n_power);
RcppExport SEXP _CellChatAccelRcpp_cellchat_prob_simple_ondemand_cpp(SEXP dataSEXP, SEXP groupSEXP, SEXP groupBootSEXP, SEXP ligandGeneSEXP, SEXP receptorGeneSEXP, SEXP KhSEXP, SEXP n_powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type groupBoot(groupBootSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ligandGene(ligandGeneSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type receptorGene(receptorGeneSEXP);
    Rcpp::traits::input_parameter< double >::type Kh(KhSEXP);
    Rcpp::traits::input_parameter< double >::type n_power(n_powerSEXP);
    rcpp_result_gen = Rcpp::wrap(cellchat_prob_simple_ondemand_cpp(data, group, groupBoot, ligandGene, receptorGene, Kh, n_power));
    return rcpp_result_gen;
END_RCPP
}
// pathway_sum_cpp
List pathway_sum_cpp(NumericVector prob, NumericVector pval, IntegerVector pathway, int n_pathways, double thresh);
RcppExport SEXP _CellChatAccelRcpp_pathway_sum_cpp(SEXP probSEXP, SEXP pvalSEXP, SEXP pathwaySEXP, SEXP n_pathwaysSEXP, SEXP threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type prob(probSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pval(pvalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pathway(pathwaySEXP);
    Rcpp::traits::input_parameter< int >::type n_pathways(n_pathwaysSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    rcpp_result_gen = Rcpp::wrap(pathway_sum_cpp(prob, pval, pathway, n_pathways, thresh));
    return rcpp_result_gen;
END_RCPP
}
// aggregate_net_cpp
List aggregate_net_cpp(NumericVector prob, NumericVector pval, double thresh);
RcppExport SEXP _CellChatAccelRcpp_aggregate_net_cpp(SEXP probSEXP, SEXP pvalSEXP, SEXP threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type prob(probSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pval(pvalSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    rcpp_result_gen = Rcpp::wrap(aggregate_net_cpp(prob, pval, thresh));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CellChatAccelRcpp_cellchat_prob_boot_cpp", (DL_FUNC) &_CellChatAccelRcpp_cellchat_prob_boot_cpp, 13},
    {"_CellChatAccelRcpp_group_tri_mean_cpp", (DL_FUNC) &_CellChatAccelRcpp_group_tri_mean_cpp, 3},
    {"_CellChatAccelRcpp_group_tri_mean_boot_cpp", (DL_FUNC) &_CellChatAccelRcpp_group_tri_mean_boot_cpp, 3},
    {"_CellChatAccelRcpp_cellchat_prob_from_avg_cpp", (DL_FUNC) &_CellChatAccelRcpp_cellchat_prob_from_avg_cpp, 12},
    {"_CellChatAccelRcpp_cellchat_prob_from_avg_sparse_cpp", (DL_FUNC) &_CellChatAccelRcpp_cellchat_prob_from_avg_sparse_cpp, 12},
    {"_CellChatAccelRcpp_cellchat_prob_sparse_stream_cpp", (DL_FUNC) &_CellChatAccelRcpp_cellchat_prob_sparse_stream_cpp, 14},
    {"_CellChatAccelRcpp_cellchat_prob_simple_ondemand_cpp", (DL_FUNC) &_CellChatAccelRcpp_cellchat_prob_simple_ondemand_cpp, 7},
    {"_CellChatAccelRcpp_pathway_sum_cpp", (DL_FUNC) &_CellChatAccelRcpp_pathway_sum_cpp, 5},
    {"_CellChatAccelRcpp_aggregate_net_cpp", (DL_FUNC) &_CellChatAccelRcpp_aggregate_net_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_CellChatAccelRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
