# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cellchat_prob_boot_cpp <- function(dataLavg, dataRavg, dataLavgBoot, dataRavgBoot, agonist, antagonist, agonistBoot, antagonistBoot, hasAgonist, hasAntagonist, Kh, n_power, nboot) {
    .Call(`_CellChatAccelRcpp_cellchat_prob_boot_cpp`, dataLavg, dataRavg, dataLavgBoot, dataRavgBoot, agonist, antagonist, agonistBoot, antagonistBoot, hasAgonist, hasAntagonist, Kh, n_power, nboot)
}

group_tri_mean_cpp <- function(data, group, K) {
    .Call(`_CellChatAccelRcpp_group_tri_mean_cpp`, data, group, K)
}

group_tri_mean_boot_cpp <- function(data, groupBoot, K) {
    .Call(`_CellChatAccelRcpp_group_tri_mean_boot_cpp`, data, groupBoot, K)
}

cellchat_prob_from_avg_cpp <- function(avg, avgBoot, ligandIdx, receptorIdx, coAIdx, coIIdx, agonistIdx, antagonistIdx, hasAgonist, hasAntagonist, Kh, n_power) {
    .Call(`_CellChatAccelRcpp_cellchat_prob_from_avg_cpp`, avg, avgBoot, ligandIdx, receptorIdx, coAIdx, coIIdx, agonistIdx, antagonistIdx, hasAgonist, hasAntagonist, Kh, n_power)
}

cellchat_prob_from_avg_sparse_cpp <- function(avg, avgBoot, ligandIdx, receptorIdx, coAIdx, coIIdx, agonistIdx, antagonistIdx, hasAgonist, hasAntagonist, Kh, n_power) {
    .Call(`_CellChatAccelRcpp_cellchat_prob_from_avg_sparse_cpp`, avg, avgBoot, ligandIdx, receptorIdx, coAIdx, coIIdx, agonistIdx, antagonistIdx, hasAgonist, hasAntagonist, Kh, n_power)
}

cellchat_prob_sparse_stream_cpp <- function(data, group, groupBoot, avg, ligandIdx, receptorIdx, coAIdx, coIIdx, agonistIdx, antagonistIdx, hasAgonist, hasAntagonist, Kh, n_power) {
    .Call(`_CellChatAccelRcpp_cellchat_prob_sparse_stream_cpp`, data, group, groupBoot, avg, ligandIdx, receptorIdx, coAIdx, coIIdx, agonistIdx, antagonistIdx, hasAgonist, hasAntagonist, Kh, n_power)
}

cellchat_prob_simple_ondemand_cpp <- function(data, group, groupBoot, ligandGene, receptorGene, Kh, n_power) {
    .Call(`_CellChatAccelRcpp_cellchat_prob_simple_ondemand_cpp`, data, group, groupBoot, ligandGene, receptorGene, Kh, n_power)
}

pathway_sum_cpp <- function(prob, pval, pathway, n_pathways, thresh) {
    .Call(`_CellChatAccelRcpp_pathway_sum_cpp`, prob, pval, pathway, n_pathways, thresh)
}

aggregate_net_cpp <- function(prob, pval, thresh) {
    .Call(`_CellChatAccelRcpp_aggregate_net_cpp`, prob, pval, thresh)
}

